// <auto-generated />
using BlazorCanvas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorCanvas.Migrations
{
    [DbContext(typeof(CanvasDbContext))]
    [Migration("20260714212457_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorCanvas.Data.Figure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("X1")
                        .HasColumnType("integer")
                        .HasColumnName("x1");

                    b.Property<int>("X2")
                        .HasColumnType("integer")
                        .HasColumnName("x2");

                    b.Property<int>("Y1")
                        .HasColumnType("integer")
                        .HasColumnName("y1");

                    b.Property<int>("Y2")
                        .HasColumnType("integer")
                        .HasColumnName("y2");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_figures_user_id");

                    b.ToTable("figures", null, t =>
                        {
                            t.HasComment("x1,y1,x2,y2 are ALWAYS the figure's bounding box. A CIRCLE is stored as the square it is inscribed in: r = (x2-x1)/2, cx = x1+r, cy = y1+r. It is DRAWN centre-out (press centre, drag for radius) but STORED as a square — interaction and storage are different things. A LINE is the segment between the two points and may run diagonally in either vertical direction; it is normalised by swapping the whole point pair, never by sorting axes.");

                            t.HasCheckConstraint("box_is_a_box", "type NOT IN ('rectangle','triangle') OR (x2 > x1 AND y2 > y1)");

                            t.HasCheckConstraint("circle_is_a_circle", "type <> 'circle' OR (x2 - x1 = y2 - y1 AND x2 > x1 AND (x2 - x1) % 2 = 0)");

                            t.HasCheckConstraint("figures_type_is_known", "type IN ('line','rectangle','circle','triangle')");

                            t.HasCheckConstraint("line_is_a_line", "type <> 'line' OR (x2 >= x1 AND (x2 > x1 OR y2 <> y1))");
                        });
                });

            modelBuilder.Entity("BlazorCanvas.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BlazorCanvas.Data.Figure", b =>
                {
                    b.HasOne("BlazorCanvas.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
