// <auto-generated />
using BlazorCanvas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#nullable disable
namespace BlazorCanvas.Migrations
{
    [DbContext(typeof(CanvasDbContext))]
    partial class CanvasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("BlazorCanvas.Data.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));
                b.Property<string>("Password").IsRequired().HasColumnType("text").HasColumnName("password");
                b.Property<string>("Username").IsRequired().HasColumnType("text").HasColumnName("username");
                b.HasKey("Id"); b.HasIndex("Username").IsUnique(); b.ToTable("users", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
