// <auto-generated />
using System;
using BlazorCanvas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorCanvas.Migrations
{
    [DbContext(typeof(CanvasDbContext))]
    partial class CanvasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorCanvas.Data.Figure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<decimal>("Z")
                        .HasColumnType("numeric")
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Z")
                        .HasDatabaseName("ix_figures_user_id_z");

                    b.ToTable("figures", null, t =>
                        {
                            t.HasComment("A figure is stored as anchor x,y plus geometry jsonb relative to that anchor: circle {r} about the centre, rectangle/triangle {w,h}, line {dx,dy}. Geometry has no database CHECK; the server is the sole writer and constructs well-formed JSON in code.");

                            t.HasCheckConstraint("figures_type_is_known", "type IN ('line','rectangle','circle','triangle')");
                        });
                });

            modelBuilder.Entity("BlazorCanvas.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BlazorCanvas.Data.Figure", b =>
                {
                    b.HasOne("BlazorCanvas.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
